### ISSUE TITLE
Performance considerations

### ISSUE THREAD

**Issue by zdnk** [arturdev/Unrealm#1]
Hello,
the tool looks good, we were doing the transition manually (from Realms `Object` subclasses to Swifts `struct`s).

But I see you are using reflection in your implementation which can cause some performance issues. I did not notice any cache for the reflection so my guess would be it might perform poorly for larger requests.

I was thinking of doing some sort of similar thing, but using `Codable`.

**Comment by arturdev** [comment]
Hi. Thanks for your feedback. 
Actually, I've tested with a Struct containing a string with a very large content (a few KBs in size) and the result was pretty promising. 
You can test it and measure yourself. 
Will appreciate if you contribute and add such Unit test to this project. 
Thanks

**Comment by jondwillis** [comment]
@zdnk Before Unrealm, I was doing something like this. Perhaps something similar could be applied to improve performance for `Codable` `Realmables` @arturdev ?

```

public protocol ModelConvertible: Codable {
    associatedtype ModelType: Codable
    func convertToModel() -> ModelType
}

extension ModelConvertible {
    public func convertToModel() -> ModelType {
        if let `self` = self as? ModelType {
            return self
        }
        let encoded = try! jsonEncoder.encode(self)
        let decoded = try! jsonDecoder.decode(ModelType.self, from: encoded)
        return decoded
    }
}


public protocol RealmConvertible {
    associatedtype RealmObjectType: Object
    func convertToRealmObject() -> RealmObjectType
}

extension Object: RealmConvertible {
    public typealias RealmObjectType = Object

    public func convertToRealmObject() -> RealmObjectType {
        return self
    }
}

extension RealmConvertible where Self: Codable, RealmObjectType: Codable {
    public func convertToRealmObject() -> RealmObjectType {
        let encoded = try! jsonEncoder.encode(self)
        let decoded = try! jsonDecoder.decode(RealmObjectType.self, from: encoded)
        return decoded
    }
}
```
