### ISSUE TITLE
Realmable migration?

### ISSUE THREAD

**Issue by bombel** [arturdev/Unrealm#12]
Is there any migration mechanism similar to Realm's one (or any at all) ? If so, how do I use it?

**Comment by arturdev** [comment]
Migration mechanism? What do you mean?

**Comment by bombel** [comment]
I mean, possibility of changing database schemas over time, as described in Realm docs https://realm.io/docs/swift/latest/#migrations .

If I understood correctly, Realmable is kind of wrapper for underlying Realm Objects. Thus, ifschema changes, these underlying object has to be migrated somehow?

**Comment by arturdev** [comment]
Oh, that's a good question. 
I'll add migration support today :)

**Comment by arturdev** [comment]
Done. 
You can do the migration exactly like before.

Say you have a struct:
```
struct Person: Realmable {
     ...
}
```

Then for migbration:
```
Realm.Configuration.defaultConfiguration = Realm.Configuration(
    schemaVersion: 1,
    migrationBlock: { migration, oldSchemaVersion in
        if (oldSchemaVersion < 1) {
            // The enumerateObjects(ofType:_:) method iterates
            // over every Person object stored in the Realm file
            migration.enumerateObjects(ofType: Person.className()) { oldObject, newObject in
                // combine name fields into a single field
                let firstName = oldObject!["firstName"] as! String
                let lastName = oldObject!["lastName"] as! String
                newObject!["fullName"] = "\(firstName) \(lastName)"
            }
        }
    })
```

**Comment by bombel** [comment]
Wow, that was quick. Cool, thanks!

**Comment by arturdev** [comment]
You're welcome ;)

**Comment by bombel** [comment]
Sorry for reopening, one more question: If I have already existing Realm database, is it possible to migrate it into your Realmable thing somehow without dropping entire database?

**Comment by arturdev** [comment]
If your old Realm classes have some prefix, then may be yes :)

**Comment by robmontesinos** [comment]
I tried to enable Migration following the above instructions regarding version 0.2.5 and got the following cocoa pod error:

[!] The platform of the target `InsightMacOS` (macOS 10.15.1) is not compatible with `Unrealm (0.2.5)`, which does not support `macOS`.

Is this library still active or should I move onto to another approach?
