### ISSUE TITLE
Is it possible to save a swift array of enums?

### ISSUE THREAD

**Issue by martinstoyanov** [arturdev/Unrealm#13]
I'm getting this error 

> Terminating app due to uncaught exception 'RLMException', reason: 'Property 'actions' is of type 'RLMArray<RLMAction>' which is not a supported RLMArray object type. RLMArrays can only contain instances of RLMObject subclasses. See https://realm.io/docs/objc/latest/#to-many for more information.'

my property actions is defined as this: 
>    var actions: [Action] = []

in a Realmable struct. `Action` is an enum that conforms to RealmableEnum

Any ideas?

**Comment by arturdev** [comment]
that's a good question... I haven't tested it, but I think it's possible. 
I'll check and add this functionality if it is missing.

**Comment by arturdev** [comment]
It seems it is hard to support saving an array of enums for now.. 
As a workaround, I can suggest you keep the second array of RawValue type of your enum. And add your actions property to ignoredProperties list. 
f.e. 

```Swift
enum Action: Int {
    ....
}

struct MyStruct: Realmable {

    private var _actions: [Int] = [] 
    var actions: [Action] {
        get {
             return _actions.compactMap({Action(rawValue: $0})
        } 
        set {
            _actions = newValue.map({$0.rawValue})
        }
    }

    static func ignoredProperties() -> [String] {
        return ["actions"]
    }
    
}
```

**Comment by martinstoyanov** [comment]
Thank you, that's exactly what I ended up doing. I hope it's supported in the future.

**Comment by bryan1anderson** [comment]
Yes this is an important piece for me. I didn't realize this wasn't a feature and got pretty frustrated trying to sift through Realm errors being thrown

**Comment by martinstoyanov** [comment]
@arturdev maybe, until it's implemented, we can add a disclaimer to the Readme with a link to this issue so people don't waste time trying to work it out? It could be a pretty cryptic error and not immediately obvious it's caused by Unrealm.

**Comment by arturdev** [comment]
@bryan1anderson @martinstoyanov Great news! ;)

**Comment by martinstoyanov** [comment]
Love it, thanks so much!!!

**Comment by arturdev** [comment]
Glad to hear that!
