### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Gargo** [arturdev/Unrealm#17]
```
[!] CocoaPods could not find compatible versions for pod "RealmSwift":
  In snapshot (Podfile.lock):
    RealmSwift (= 4.1.1)

  In Podfile:
    RealmSwift

    Unrealm was resolved to 0.1.0, which depends on
      RealmSwift (= 3.15.0)
```

**Comment by arturdev** [comment]
Can you share with me your podfile?

**Comment by Gargo** [comment]
@arturdev podfile:
```
pod 'RealmSwift'
pod 'Unrealm'
```
You should at least update 'Unrealm' to make it using Realm 4.x versions

**Comment by arturdev** [comment]
You don't need `pod 'RealmSwift'`

**Comment by Gargo** [comment]
@arturdev ok, but I also want `RealmSwift` of the actual version. If your library doesn't support the latest realm and you don't plan to fix it then you should at least mention it in Readme

**Comment by arturdev** [comment]
I plan to add support of latest version. Will add in readme currently supported version.
