### ISSUE TITLE
LinkingObjects support?

### ISSUE THREAD

**Issue by jondwillis** [arturdev/Unrealm#18]
Is there a way to use `LinkingObjects`? 

`LinkingObjects` expects an `Object` type.

Happy to help implement this, I imagine it would require wrapping `LinkingObjects` to be compatible with `Realmable` instead of `Object`.

**Comment by arturdev** [comment]
Currently I'm trying to support the latest version of Realm (4.x.x) (they have made a breaking change in the method of reading property names from a class). So any help is appreciated. 
Thanks!

**Comment by jondwillis** [comment]
@arturdev can you describe the breaking change?

**Comment by arturdev** [comment]
@jondwillis 
https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Object.swift#L669-L694
Previously they was fetching property list by using ObjcRuntime, but now they use Swift's Reflection Api (Mirror). 
The logic behind Unrealm is the following: create an ObjC class named "RLM" + <YourStructName> inherited from Realm's `Object` clsdd with the same properties that has your swifty struct/class at RUNTIME. 
The thing is that Mirroring returns an empty children for non-swift types which is our case, becuase the end-class that is being passed to Realm is purely ObjC class made with objc_allocateClassPair/objc_registerClassPair. So we need to find a way to solve this.

**Comment by arturdev** [comment]
@jondwillis Happy to announce that it is fixed now and RealmCocoa's version is bumped to the latest on!

**Comment by arturdev** [comment]
I'm closing this issue since Unrealm will not support LinkingObjects for near future
