### ISSUE TITLE
Use newer RealmSwift?

### ISSUE THREAD

**Issue by martinstoyanov** [arturdev/Unrealm#19]
Currently Unrealm is on 3.18.0. There is 4.3.0 and even 5.0.0 beta.

https://github.com/realm/realm-cocoa/releases

**Comment by arturdev** [comment]
I know. Starting from 4.0 there is a breaking change in Object.swift which breaks Unrealm, that's why I didn't update yet.

**Comment by arturdev** [comment]
@martinstoyanov I've bumped version to 4.3.0. 
Though Travis keeps failing, the unit tests pass successfully on my local machine. 
You will be very helpful if you test on your side as well and share the results. 
Thanks!

**Comment by martinstoyanov** [comment]
Amazing, thank you!

**Comment by martinstoyanov** [comment]
@arturdev I upgraded and I am getting errors with primary keys:

"Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'id' does not exist on object 'RLMBuddy''"

This is what `Buddy` looks like:

`
struct Buddy: Realmable, Codable {
    var id: String = ""
    var userId: String = ""
    var name: String = ""
    var phoneNumber: String = ""
    
    static func primaryKey() -> String? {
        return "id"
    }
}`

Any advice?

**Comment by arturdev** [comment]
That's not good. What is your Xcode version?

**Comment by arturdev** [comment]
@martinstoyanov

**Comment by arturdev** [comment]
@martinstoyanov  Updated to 1.0.1. Travis is green now. Please confirm that it works on your side as well. Thanks!
