### ISSUE TITLE
error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by ahmadmssm** [arturdev/Unrealm#2]
```
let cls = (NSClassFromString(realmClass) ?? NSClassFromString(realmTypeName)) as! Object.Type
```

error: Unexpectedly found nil while unwrapping an Optional value

**Comment by arturdev** [comment]
Please make sure you've registered your Realmable type in AppDelegate's didFinishLaunching method as described in Readme

**Comment by arturdev** [comment]
I'll close this issue in 2 days due to inactivity

**Comment by ahmadmssm** [comment]
@arturdev I already registered Realmable type in AppDelegate's didFinishLaunching method as described in Read me but i found this issue.

**Comment by arturdev** [comment]
@ahmadmssm so everything works now?

**Comment by ahmadmssm** [comment]
@arturdev  No, i was telling you that i get this issue although i have already registered Realmable type in AppDelegate's didFinishLaunching method

**Comment by arturdev** [comment]
Can you please make an example project which demonstrates that issue? 
Thanks

**Comment by arturdev** [comment]
@ahmadmssm Can you please make an example project which demonstrates that issue? 
Thanks

**Comment by ahmadmssm** [comment]
@arturdev I can till you the thing which leads to this bug, 
I made a base model class that conforms to both ```Decodable``` and ```Realmable``` and make all my model classes extend this base class, After i did so, this issue happened.

**Comment by danialmoghaddam** [comment]
@arturdev how does Unrealm behave in case nill option swift primitive? could this be the case?

**Comment by arturdev** [comment]
@ahmadmssm I've tested the case as you've described and I haven't get any crash. 
Can you please send an example project?

**Comment by arturdev** [comment]
@danialmoghaddam I don't think so.

**Comment by arturdev** [comment]
@ahmadmssm  I'm still unable to reproduce this issue. 
When you have time, please send an example project. 
Thanks.

**Comment by ahmadmssm** [comment]
@arturdev I'm a little bit busy but i will try to upload a sample example soon, thanks for following up with me

**Comment by arturdev** [comment]
@ahmadmssm Thank you too for your help to make this library as bugless as possible. 
Appreciate it!

**Comment by arturdev** [comment]
@ahmadmssm Have you got a chance to make a sample project?

**Comment by ahmadmssm** [comment]
@arturdev I will try to upload a sample within this week

**Comment by ahmadmssm** [comment]
https://drive.google.com/file/d/1MnVOoi9wWdrYhWL6A4EKy76snjyLO3kz/view?usp=sharing

**Comment by arturdev** [comment]
@ahmadmssm Thank you very much!
Please update to the latest version (0.2.1). 
Also, I've noticed an issue in your code:
BaseRealmTable.swift, line: 42. 
replace this:
`self.realm.add(records)`
with 
`self.realm.add(records, update: true)` 
Because by default it is INSERT query and not INSERT OR UPDATE, which means that your app will crash if you try to add an object which already exists (an object with the same primary key). 

Please update and confirm if it worked.
Thanks.

**Comment by arturdev** [comment]
@ahmadmssm Have you got a chance to test it? 
I'll close this issue in 2 days.

**Comment by ahmadmssm** [comment]
@arturdev If you do not mind, please give me until the end of next week and i will close it if it is working.

**Comment by arturdev** [comment]
@ahmadmssm sure

**Comment by ahmadmssm** [comment]
@arturdev Thanks, it is working now and i can close it, however it refuses to update to version to 0.2.1 and the message is can not find compatible version

**Comment by arturdev** [comment]
Oh, currently the latest version is 0.2.4 :)
