### ISSUE TITLE
enums not working

### ISSUE THREAD

**Issue by af2446** [arturdev/Unrealm#20]
i try to use enum inside an object and it's returning the following error

> Terminating app due to uncaught exception 'RLMException', reason: 'Property 'type' is declared as 'RLMnone', which is not a supported RLMObject property type. All properties must be primitives, NSString, NSDate, NSData, NSNumber, RLMArray, RLMLinkingObjects, or subclasses of RLMObject. See https://realm.io/docs/objc/latest/api/Classes/RLMObject.html for more information.'

error STACK: 

> (
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   Realm                               0x0000000110d97ff1 -[RLMProperty setTypeFromRawType:] + 2673
	3   Realm                               0x0000000110d99101 -[RLMProperty initSwiftPropertyWithName:indexed:linkPropertyDescriptor:property:instance:] + 2673
	4   Realm                               0x0000000110d6f3ba +[RLMObjectSchema propertiesForClass:isSwift:] + 1594
	5   Realm                               0x0000000110d6d43e +[RLMObjectSchema schemaForObjectClass:] + 942
	6   Realm                               0x0000000110e99c4e _ZL16RLMRegisterClassP10objc_class + 302
	7   Realm                               0x0000000110e9ac7d __25+[RLMSchema sharedSchema]_block_invoke + 77
	8   CoreFoundation                      0x00007fff23cd7c37 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	9   CoreFoundation                      0x00007fff23cb0dce -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 238
	10  Realm                               0x0000000110e9a9bf +[RLMSchema sharedSchema] + 479
	11  Realm                               0x0000000110e60fd5 +[RLMRealm realmWithConfiguration:error:] + 2805
	12  RealmSwift                          0x000000011251fe01 $sSo8RLMRealmC13configurationABSo0A13ConfigurationC_tKcfCTO + 145
	13  RealmSwift                          0x000000011251fcb5 $s10RealmSwift0A0VACyKcfC + 101
	14  Dev-◊î◊û◊ß◊¶◊¢◊ï◊†◊ô◊ù              0x000000010dca85e1 $s7Pro_Dev20RealmDataBaseManagerC14saveMikiSearch04mikiI0yAA0hI0Vz_tF + 161
	15  Dev-◊î◊û◊ß◊¶◊¢◊ï◊†◊ô◊ù              0x000000010d96cd7f $s7Pro_Dev22LeftMenuViewControllerC11onItemClick4itemyAA0adH0C_tF + 1359
	16  Dev-◊î◊û◊ß◊¶◊¢◊ï◊†◊ô◊ù              0x000000010d9728d5 $s7Pro_Dev22LeftMenuViewControllerCAA0d5TableE8ProtocolA2aDP11onItemClick4itemyAA0adJ0C_tFTW + 37
	17  Dev-◊î◊û◊ß◊¶◊¢◊ï◊†◊ô◊ù              0x000000010dfa2185 $s7Pro_Dev13MenuTableViewC05tableE0_14didSelectRowAtySo07UITableE0C_10Foundation9IndexPathVtF + 517
	18  Dev-◊î◊û◊ß◊¶◊¢◊ï◊†◊ô◊ù              0x000000010dfa22c7 $s7Pro_Dev13MenuTableViewC05tableE0_14didSelectRowAtySo07UITableE0C_10Foundation9IndexPathVtFTo + 167
	19  UIKitCore                           0x00007fff47a37657 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:isCellMultiSelect:] + 855
	20  UIKitCore                           0x00007fff47a372e9 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 97
	21  UIKitCore                           0x00007fff47a37b14 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 334
	22  UIKitCore                           0x00007fff47858d48 _runAfterCACommitDeferredBlocks + 352
	23  UIKitCore                           0x00007fff478494ec _cleanUpAfterCAFlushAndRunDeferredBlocks + 248
	24  UIKitCore                           0x00007fff47879365 _afterCACommitHandler + 85
	25  CoreFoundation                      0x00007fff23bb1617 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	26  CoreFoundation                      0x00007fff23bac0ae __CFRunLoopDoObservers + 430
	27  CoreFoundation                      0x00007fff23bac72a __CFRunLoopRun + 1514
	28  CoreFoundation                      0x00007fff23babe16 CFRunLoopRunSpecific + 438
	29  GraphicsServices                    0x00007fff38438bb0 GSEventRunModal + 65
	30  UIKitCore                           0x00007fff4784fb48 UIApplicationMain + 1621
	31  Dev-◊î◊û◊ß◊¶◊¢◊ï◊†◊ô◊ù              0x000000010ddebe8a main + 490
	32  libdyld.dylib                       0x00007fff51a1dc25 start + 1
	33  ???                                 0x0000000000000005 0x0 + 5
)

ENUM im trying to insert:
`

import Foundation
import Unrealm

class MikiDate : MikiDateListable, Realmable {
    required init() {
        
    }
    
    static func == (lhs: MikiDate, rhs: MikiDate) -> Bool {
        return true
    }
    
    
    enum DateType: Int, Realmable {
        init() {
            self = .none
        }        
        case none = 0
        case now
        case today
        case tomorrow
        case laterDate
        case rangeDate
    }
    
    var text : String?
    var checked = false
    var type = DateType.none
    
    init(type: DateType) {
        self.type = type
    }

    //MARK: MikiListable
    func mikiText() -> String? {
        switch type {
            case .now:
                return "עכשיו - שיגיע דחוף"
            case .today:
                return "היום"
            case .tomorrow:
                return "מחר"
            case .laterDate:
                return "תאריך אחר"
            case .rangeDate:
                return "טווח תאריכים"
            default:
                return ""
        }
    }
    
    func isChecked() -> Bool {
        return checked
    }
}
`

**Comment by arturdev** [comment]
All enums should conform to `RealmableEnum`
https://github.com/arturdev/Unrealm#usage

**Comment by arturdev** [comment]
@af2446 Please lmk about results
