### ISSUE TITLE
Installing as a SwiftPackage fails

### ISSUE THREAD

**Issue by JARMourato** [arturdev/Unrealm#21]
Tried Installing by adding this line: 
`.package(url: "https://github.com/arturdev/Unrealm", from: "1.0.1")`

or this (since the line above does not use the latest version that includes Realm 4.3.0)

``.package(url: "https://github.com/arturdev/Unrealm", .branch("master"))``

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/7236944/73412584-f48a8080-4300-11ea-8124-78f3650230a6.png">

**Comment by arturdev** [comment]
Can you please try from tag v0.2.5?

**Comment by JARMourato** [comment]
using that tag works @arturdev - but then I'll be using an outdated version

**Comment by arturdev** [comment]
I will update SPM in a few hours.. stay tuned

**Comment by arturdev** [comment]
Please try again. I released a new version: [1.0.2](https://github.com/arturdev/Unrealm/releases/tag/1.0.2)

**Comment by JARMourato** [comment]
I tried 1.0.2 and I still got the error from the image above when building.

**Comment by arturdev** [comment]
Found the reason.. The thing is that SPM currently doesn't support importing Swift package target into ObjC package target. 
So if you want to use Unrealm with RealmSwift's latest version, you should install it by cocoapods.
