### ISSUE TITLE
Problem with JSONSerialization with Int as key

### ISSUE THREAD

**Issue by Jerry64** [arturdev/Unrealm#22]
Hello,
I'm migrating my Object models to Realmable, but I have a problem with a data type I'm trying to save.

I have a data model defined like this :

` struct WorkoutRoutine: Realmable, Codable {

    var id: String = UUID().uuidString
    var name: String = ""
    var bodyPart: String = ""

    var type: String = "normal"
    var globalRestTimer: Double = 0.0
    var exerciseSpecificRestTimer: [Int: Double] = [0: 0.0]

    var exercises: [Exercise]?
    var exercisesTargetSets: [Int: Int] = [0:0]
    var exercisesTargetReps: [Int: Int] = [0:0]

    var createdAt: Date = Date()
    
    static func primaryKey() -> String? {
        return "id"

    }
}`

It crashes when it's trying to serialize my object as JSON. I think it's due to the fact that the keys are required to be of type NSString (when serializing with JSONSerialization), and I'm using "Int". How could they be converted automatically?

I'm not sure how to convert it to a string. When I take my model and encode it using JSONEncoder, it produces valid JSON.

Here are some screenshot of the Exception Breakpoint:

![Screen Shot 2020-02-01 at 3 40 21 PM](https://user-images.githubusercontent.com/5474100/73598660-34bc4f80-4509-11ea-9304-c4c9cc33f0ea.png)
![Screen Shot 2020-02-01 at 3 40 21 PM](https://user-images.githubusercontent.com/5474100/73598762-5407ac80-450a-11ea-97ea-94e0f155c20f.png)
![Screen Shot 2020-02-01 at 3 44 38 PM](https://user-images.githubusercontent.com/5474100/73598763-5407ac80-450a-11ea-8042-c2bf566f56b2.png)

**Comment by arturdev** [comment]
I just released v1.0.3. Please update on your side and try again.

**Comment by Jerry64** [comment]
Thanks for your quick answer!

The same exception gets thrown, but this time, the exception is not throwing inside 
`realm.add()`,

and I can't find where it is called from exactly.

![Screen Shot 2020-02-02 at 12 51 42 PM](https://user-images.githubusercontent.com/5474100/73612567-d485e600-45ba-11ea-8009-6ea71d03f0a4.png)

**Comment by Jerry64** [comment]
Okay, that's weird.

The method `convert` does not get called anymore, that's why it's not throwing anymore.

I'm doing a clean build to see if that might be the issue.

**Comment by Jerry64** [comment]
Okay, so that seemed to have done the trick.

It was probably using an old cached version of the model, with invalid keys (Int). A clean build did the trick.

Thanks a lot!!

**Comment by arturdev** [comment]
Thank you for finding this bug! ;)
