### ISSUE TITLE
Problem with NSKeyedArchiver

### ISSUE THREAD

**Issue by Jerry64** [arturdev/Unrealm#24]
Hi,

I'm trying to save a simple model to the Realm, but somehow, the new version using NsKeyedArchiver is throwing an exception.

`Error Domain=NSCocoaErrorDomain Code=4866 "The data couldn’t be written because it isn’t in the correct format." UserInfo={NSUnderlyingError=0x60000168e8e0 {Error Domain=NSCocoaErrorDomain Code=4864 "This decoder will only decode classes that adopt NSSecureCoding. Class '__SwiftValue' does not adopt it." UserInfo={NSDebugDescription=This decoder will only decode classes that adopt NSSecureCoding. Class '__SwiftValue' does not adopt it.}}}`

Here's and exemple of the model I'm trying to save.

`struct Model: Realmable, Codable {
    
    var id: String = UUID().uuidString
    var name: String = ""
    var cat: String = "default"
    
    var type: String = "user"
    
    var dictionary: [Int: [SomeArray]] = [:]
    
    var startDate: Date?
    var endDate: Date?
    
    static func primaryKey() -> String? {
        return "id"
    }
}`

It will save the model, but the `dictionary` variable will be nil.

I'm stuck there, I have tried many different solution but I won't work.

Thanks !

**Comment by arturdev** [comment]
Does the problem exist even if you change `SomeArray` with `String`?

**Comment by Jerry64** [comment]
It's working just fine when changing it to a `String`.

**Comment by Jerry64** [comment]
I'm trying to save an object from another model, inside an array, inside that dictionary.

So basically, this is what i'm trying to achieve:

`var dictionary: [Int: [DataModel]] = [:]` :

`struct DataModel: Realmable, Codable {

}

**Comment by arturdev** [comment]
Currently saving an array of objects in a dictionary is not supported. 
As a workaround, I can suggest you do the following: 
1.  Add a new private variable with type: [Int: String] (say `var underlyingDic: [Int: String] = [:]`
1. Add your old variable to the ignored list 
3. In the setter of your old variable convert your array of `Codable`s  to json string, and assign to the newly created variable 
4. In  the getter of your old variable read the json string form the newly created var and convert it back.

**Comment by Jerry64** [comment]
Hi !

Sorry for the late answer. I've implemented your idea, and it's working like a charm. Nice workaround that'll do the trick for now.

I hadn't thought about it.

Thanks for your help. I'll let you close the issue if you want to close it, or leave it open for now.
