### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by flocked** [arturdev/Unrealm#26]
Would it be possible to add MacOS support to Unrealm. Which area of the code is currently preventing Unrealm to run on Mac and needs to be adopt?

Thanks,

**Comment by arturdev** [comment]
In theory, it should also work on macOS. I haven't used anything iOS specific. 
You just need to try it.
Please update the issue after.
Thanks

**Comment by arturdev** [comment]
@flocked From now on Unrealm supports macOS  as well!

**Comment by flocked** [comment]
Wow that was fast. Thanks :)
