### ISSUE TITLE
Add support for Swift Package Manager for the latest version? 

### ISSUE THREAD

**Issue by martinstoyanov** [arturdev/Unrealm#28]
Possible to add support not just for 0.2.5? Thanks! This is what I get now if I try to build SPM unrealm on Catalyst:

<img width="1492" alt="Screen Shot 2020-04-17 at 10 12 11 PM" src="https://user-images.githubusercontent.com/7541813/79625663-7d42dc80-80f8-11ea-90f0-8fbe00883234.png">

**Comment by arturdev** [comment]
Unfortunately no, it is not possible at the moment

**Comment by arturdev** [comment]
@martinstoyanov Can you please test it from the [SPM](https://github.com/arturdev/Unrealm/tree/SPM) branch?

**Comment by martinstoyanov** [comment]
@arturdev Tested and works like a charm. Thank you very much!!!

**Comment by arturdev** [comment]
Thank you too!!
