### ISSUE TITLE
Casting custom class fails.

### ISSUE THREAD

**Issue by Priva28** [arturdev/Unrealm#29]
I'm not sure if this is just an error with my code but I have a Realmable that looks like this:

```
struct AnyEntity: Realmable {
    
    var id: String = ""
    var state: String = ""
    
    var attributes: EntityAttributes? = nil
    
    static func primaryKey() -> String? {
        return "id"
    }
}
```

The attributes is a class that looks like this:
```
class EntityAttributes: Realmable {
    required init() {
    }
}
```

and multiple other custom classes can inherit from EntityAttributes like this:
```
class LightAttributes: EntityAttributes {
    var brightness: Int? = nil
    var rgbColor: [Int]? = nil
}
```

Now when I save say for example a LightEntity, as the attributes variable of the AnyEntity Realmable this works fine.

```
let realm = try! Realm()
                    
let attributes = LightAttributes()
attributes.brightness = 1
attributes.rgbColor = [0, 255, 255]
                    
let newEntity = AnyEntity(entityId: "entity_0", state: "abc", attributes: attributes)
                    
try! realm.write {
    realm.add(newEntity, update: .modified)
}
```

But when I try to access the saved and cast the attributes variable from EntityAttributes to LightAttributes, it fails.
```
let realm = try! Realm()

let entity = realm.object(ofType: AnyEntity.self, forPrimaryKey: "entity_0")

// Fails with "Could not cast value of type 'EntityAttributes' (0x1041bf2f0) to 'LightAttributes' (0x1041bf380)."
let attributes = entity!.attributes as! LightEntity
```

**Comment by arturdev** [comment]
@Priva28 Thanks for opening this issue. Can you please provide a small demo project where I can reproduce this issue?

**Comment by arturdev** [comment]
The thing is that Realm itself doesn't support inheritance fully. In your case you're trying to save a an object of a derived class into another realmable object, which Realm doesn't support. 
So this issue is more relevant to them ([RealmCocoa](https://github.com/realm/realm-cocoa)) rather to Unrealm.
