### ISSUE TITLE
Can't find Unrealm in cocoapods

### ISSUE THREAD

**Issue by icefox57** [arturdev/Unrealm#3]
![image](https://user-images.githubusercontent.com/1716737/60246409-38dc1b00-98f1-11e9-89c1-fe55f38ab84c.png)

**Comment by icefox57** [comment]
I can't find unrealm use pod search command and cocoapod.org ,  but it can be install

**Comment by arturdev** [comment]
@icefox57 https://cocoapods.org/pods/Unrealm
