### ISSUE TITLE
Question: Does Unrealm support Realm objects with optional properties?

### ISSUE THREAD

**Issue by lingolab2** [arturdev/Unrealm#30]
Question: Does Unrealm support Realm objects with optional properties?
e.g.
struct Jukugo: Realmable {
  public let id: Int? = 0
  public let nameString: String? = ""
  public let address: String? = ""
  public let pinCode: Int? = 0
  
  static func primaryKey() -> String?
  {
    return "id"
  }
}

**Comment by arturdev** [comment]
Yes, it does.
Are you facing any issue with it?

**Comment by lingolab2** [comment]
This is my code extract and no warnings or errors. I don’t know if it’s a Unrealm usage issue or a Realm usage issue.

import Foundation
import Unrealm
import Realm
import RealmSwift

struct Jukugo: Realmable {
  public let id: Int? = 0
  public let jukugoString: String? = “"
  ...
  public let frequency: Int? = 0
  
  static func primaryKey() -> String?
  {
    return "id"
  }
}

func initializeDatabase() {
  
  let config = Realm.Configuration(
      schemaVersion: 1,
      migrationBlock: { migration, oldSchemaVersion in
          if (oldSchemaVersion < 1) {
          }
      })
   
  Realm.Configuration.defaultConfiguration = config
  let realm:Realm = {
      return try! Realm()
  }()
  
  let jukugos = realm.objects(Jukugo.self)
  print(jukugos.count) // I am getting 0 here when should be 29000
}

**Comment by arturdev** [comment]
Have you added any object of type `Jukugo` before?

**Comment by lingolab2** [comment]
No, I have a pre-existing populated database created by RealmStudio from a csv-file.
I have done this as well:
    Realm.registerRealmables(Jukugo.self)

**Comment by arturdev** [comment]
The way Unrealm works is that it created an objective-c pair class with RLM prefix for every Realmable you register. F.e. in your case it creates a class named `RLMJukugo`. So if you're creating object outside of the app make sure that the table name is `RLMJukugo` and not just `Jukugo`

**Comment by lingolab2** [comment]
I've renamed, recreated and embedded the realm database within the app bundle.
I still face the issue. I think I have something basically wrong. No realm errors/warnings.
But no rows returned.
![Screenshot 2020-05-06 at 19 14 57](https://user-images.githubusercontent.com/29536555/81184460-0fd6ed00-8fce-11ea-80c9-b86d1a468905.png)

**Comment by lingolab2** [comment]
I've renamed, recreated and embedded the realm database within the app bundle.
I still face the issue. I think I have something basically wrong. No realm errors/warnings.
But no rows returned. (sorry closed it by mistake earlier)
![Screenshot 2020-05-06 at 19 14 57](https://user-images.githubusercontent.com/29536555/81184769-6cd2a300-8fce-11ea-91ee-23c61dd5cf76.png)

**Comment by arturdev** [comment]
Can you send me an example project with the db you created?

**Comment by lingolab2** [comment]
[default.realm.zip](https://github.com/arturdev/Unrealm/files/4587223/default.realm.zip)

**Comment by lingolab2** [comment]
![Screenshot 2020-05-06 at 19 24 16](https://user-images.githubusercontent.com/29536555/81186869-f2efe900-8fd0-11ea-963d-3cf7ed197a59.png)

**Comment by lingolab2** [comment]
[ToGitHub.zip](https://github.com/arturdev/Unrealm/files/4587263/ToGitHub.zip)

**Comment by arturdev** [comment]
Few issues here.. 
At first, you need to copy the bundled realm to a place from where Realm can read it.
Secondly, you need to configure the Realm property by setting the right URL for the copied realm db.
And third, in the default.realm you've attached the `id` field is of type `Int?`, but primary keys can't be an optional type! So something went front during importing from csv, as id must be `int` and not `int?`.
![image](https://user-images.githubusercontent.com/6263856/81217130-25a7da80-8fed-11ea-8745-fcdee58c99d8.png)

See the working example project (mainly in AppDelegate).
[JukugoExample.zip](https://github.com/arturdev/Unrealm/files/4588913/JukugoExample.zip)

**Comment by lingolab2** [comment]
As mentioned by you, it's indeed a working example. I did notice that RealmStudio is generating optionals for all fields when converting from CSV, and I'll figure out why. Please close this and thank you for all your help.

**Comment by arturdev** [comment]
You're welcome!
