### ISSUE TITLE
How to fetch swift dictionary stored in realm ?

### ISSUE THREAD

**Issue by Venkata-Maniteja** [arturdev/Unrealm#31]
I have this field in a struct Contact.

var customFields: [String: String?]?

I'm able to store this field in realm.  It is storing as data field. 

But when I try to fetch the contact and read it, the custom fields are empty. 

Do I have to manually convert data. back into swift dicionary ?

At which level, do I have to do this conversion ?

Info:

At the line:

      let results = self.objects(cls)

when I do, po results.first, I can see the customField with some data in it.

customFields = <length = 24, bytes = 0x62706c6973743030d4010203040506070a58247665727369 — 1537 total bytes>;

Now after Results(rlmResult: results) happens, 

the struct shows customFields as nil.

Not sure how I intercept  and do the conversion of data to dictionary. 

Update:

Able to get it by tweaking a part of the code.

 ```
if let data = value as? Data { 

    //works
if let json = try NSKeyedUnarchiver.unarchiveTopLevelObjectWithData(data) {
                                    try property.set(value: json, on: &self)
                                }

}
```

For some reason  child.value is [AnyHashable:Any] is nil and this condition fails .

**Comment by arturdev** [comment]
Actually Unrealm should do all the conversions automatically. If you can provide an example project where I can reproduce this issue, probably I can fix that.

**Comment by Venkata-Maniteja** [comment]
@arturdev HEre is the sample one. It has a sample realm db with demo data and a method to fetch 
[TestUnRealm.zip](https://github.com/arturdev/Unrealm/files/4627850/TestUnRealm.zip)
the data back.

**Comment by arturdev** [comment]
You're using SPM or cocoapods?

**Comment by Venkata-Maniteja** [comment]
@arturdev I tried cocopods, but it gave me not supported to macos target. So I ddonwloaded the source, and added in the project manually. I tried the latest release.

**Comment by arturdev** [comment]
Actually the latest pod version supports macos targets

**Comment by arturdev** [comment]
Ok so the issues are the following: 
At first, Unrealm doesn't support optional Dictionaries yet. Secondly, as you've set `id` as primary key, it can't be optional.

See the working project.
[TestUnRealm.zip](https://github.com/arturdev/Unrealm/files/4637137/TestUnRealm.zip)

**Comment by Venkata-Maniteja** [comment]
awesome, thanks for the quick response.  I'll try that.
