### ISSUE TITLE
__nilProperties

### ISSUE THREAD

**Issue by zeitoun26** [arturdev/Unrealm#33]
Hello. I'm curious why was this code below added? I reinstalled my app and it worked but just curious why I have this in my database now. It's just an empty array so not sure what it's for.

	addPropertyToClassIfNeeded(className: className, name: "__nilProperties", typeStr: "Array<String>")

**Comment by arturdev** [comment]
Hi. This property is added by Unrealm for the proper handling of the optional Swift specific properties (like optional Swift Arrays, dictionaries, etc..). This is private property and you should not take attention to it ;)
