### ISSUE TITLE
Configure realm class prefix

### ISSUE THREAD

**Issue by Tommecpe** [arturdev/Unrealm#34]
Thank you for your awesome Lib ! really nice to use.

I have a question: is there a way to change the `realmClassPrefix` set at **"RLM"** in `RealmableBase` ?

I'm using a full-sync read-only Realm and cannot change the classe name: "myClasse". So I would Like to set the `realmClassPrefix` to ""

I've tried:

```
extension MyClasse: Realmable {
    static func className() -> String { "myClasse" }
}
```

But It doesn't seam to affect the classe name.

I've also tried:

```
extension MyClasse: Realmable {
   static var realmClassPrefix: String { "My" }
}
```

But it seam to crash my app :/

**Comment by arturdev** [comment]
The only way to change the RLM prefix is by overriding the realmClassPrefix method
