### ISSUE TITLE
How to save `Enum` type ?

### ISSUE THREAD

**Issue by linkfei** [arturdev/Unrealm#4]
Terminating app due to uncaught exception 'RLMException', reason: 'Can't persist property 'type' with incompatible type. Add to Object.ignoredProperties() class method to ignore.'
*** First throw call stack:

**Comment by arturdev** [comment]
Example: https://github.com/arturdev/Unrealm/blob/master/Example/Tests/ExampleModels/User.swift

**Comment by arturdev** [comment]
@linkfei  please let me know if it works
