### ISSUE TITLE
Optional Enum Problem

### ISSUE THREAD

**Issue by AngCosmin** [arturdev/Unrealm#40]
Hey @arturdev 

I found this library and it's awesome! But I found a small issue (I think 😅).

I am having this enum and I registerd it inside AppDelegate

```swift
enum AgeRange: String, Codable, RealmableEnumString {
    case KID = "13-15"
    case TEENAGER = "16-18"
    case YOUNG_ADULT = "19-25"
    case LATE_TWENTIES = "26-30"
    case THIRTIES = "31-40"
    case MIDDLE_AGED = "41-60"
    case SENIOR = "60+"
}
```

And this class which is using the enum. (also registered)

```swift
final class PatientModel: Codable, Realmable {
    var uuid: String = ""
    var firstName: String?
    var lastName: String?
    var ageRange: AgeRange?
}
```

And I am getting this error at the build time

```
*** Terminating app due to uncaught exception 'RLMException', reason: 'Property 'ageRange' is declared as 'AgeRange', which is not a supported RLMObject property type. All properties must be primitives, NSString, NSDate, NSData, NSNumber, RLMArray, RLMLinkingObjects, or subclasses of RLMObject. See https://realm.io/docs/objc/latest/api/Classes/RLMObject.html for more information.'
```

It's a little bit strange because if I declare it as `var ageRange: AgeRange` (without optional) or `var ageRange: [AgeRange]? = nil` everything it's working. 

I found a workaround by encoding and decoding manually, but it's a lot of work because I have many other fields inside `PatientModel` and it's a little bit annoying to write them again and again.

```swift
if let range = try container.decodeIfPresent(AgeRange.self, forKey: .ageRange) {
    self.ageRange = range
} else {
    self.ageRange = .KID
}
```

Am I missing something? 

Thanks 😁

**Comment by arturdev** [comment]
Hi. 
What is `RealmableEnumString`?

**Comment by AngCosmin** [comment]
Hey, 

Thanks for the answear. It's from your library:

https://github.com/arturdev/Unrealm/blob/master/Unrealm/Classes/Swift/Unrealm.swift#L31

I also tried with `RealmableEnum` and it's still not working

**Comment by ArthurHenriqueVieira** [comment]
Hello, any answer for this question?

**Comment by arturdev** [comment]
I'm afraid optional enums are not supported currently
