### ISSUE TITLE
Realm 10 support?

### ISSUE THREAD

**Issue by martinstoyanov** [arturdev/Unrealm#46]
Hi! Any plans for including Realm 10.x support?

**Comment by arturdev** [comment]
Hi. Yes, I'm working on it. In a few days will update the podfile

**Comment by pushchris** [comment]
Are there any updates to when support for Realm 10.x will be available?

**Comment by arturdev** [comment]
They have done some breaking change. So can tell when exactly the new version will be ready..

**Comment by arturdev** [comment]
I've finally solved it and updated Realm version to the latest one

**Comment by martinstoyanov** [comment]
Woo you're the best @arturdev ! Happy holidays! 🎄🎄🥳
