### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by mladjan** [arturdev/Unrealm#48]
I have hit a performance issue with Unrealm. My Structure is:

Stint (1 instance only):
    - Has 8 Lap relations (one to many)
            - Lap has 3k - 6k location objects (one to many)

When I do something simple like:
`        let stints = realm.objects(Stint.self)
        
        for stint in stints{
            if(stint.laps.count>0){
                allStints.append(stint)
            }
        }
`
It takes 2s to go through this **for loop**.

What is the best approach you suggest for optimizing this?

**Comment by arturdev** [comment]
Are you sure that this is related to Unrealm? This library shouldn't impact on the performance of loops
