### ISSUE TITLE
Unrealm pod for Xcode11 Beta 5

### ISSUE THREAD

**Issue by Hurobaki** [arturdev/Unrealm#5]
Hello,

I try to install Unrealm in Xcode11 Beta 5. When I try to instanciate `Realm()` it throws me an error : **Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'name' does not exist on object 'RealmSwiftClassPermission''**

I saw that is because Realm and RealmSwift has to be explicitly add to Podfile to target Xcode11.
 
Podfile :
```
pod 'Unrealm'
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'tg/xcode-11-b1', submodules: true

pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'tg/xcode-11-b1', submodules: true
```

But now I got the following error : **Unrealm was resolved to 0.1.0, which depends on
      RealmSwift (= 3.15.0) was resolved to 3.15.0, which depends on
        Realm (= 3.15.0)**

I think it's because Unrealm pod doesn't support Xcode11. Is that correct ?

**Comment by arturdev** [comment]
Yes, currently I've not tested/optimized it for Xcode11.  
But it seems Realm issue: https://github.com/realm/realm-cocoa/issues/6163. 
Anyway, I will update the realm version to the latest one soon (currently Unrealm uses 3.15.0 version of Realm).

**Comment by judges** [comment]
Any updates?

**Comment by arturdev** [comment]
@judges today or tomorrow will update

**Comment by arturdev** [comment]
@Hurobaki @judges  
The new version is released!
Please update to the latest version and try again.
