### ISSUE TITLE
CGFloat, CGPoint, CGSize.. tuples ?

### ISSUE THREAD

**Issue by quentinfasquel** [arturdev/Unrealm#50]
Hey there,

I am trying to have a simple struct to be Realmable...

```
struct Sprite: Realmable {
    let id: String
    let position: CGPoint
    let size: CGSize
    let alpha: CGFloat
  
    static fun primaryKey() -> String { "id" }
}
```

I am adding extension `RealmableEnum` on each of these, matching Float, tried with `NSNumber(cgPoint: )` and with `NSCoder.string(cgPoint:)`.. is there a way to do so ?

Or should I basically just save JSON strings for each object, generated by Codable ?.. sounds less efficient to me

**Comment by arturdev** [comment]
Can you please be more specific what is the issue here?

**Comment by quentinfasquel** [comment]
```
    func testCoreGraphicsTypes() {
        struct Sprite: Realmable {
            var id: String = UUID().uuidString
            var position: CGPoint = .zero
            var size: CGSize = .zero
            var alpha: CGFloat = 0
          
            static func primaryKey() -> String { "id" }
        }

        Realm.registerRealmables(Sprite.self)
        
        let sprite = Sprite()

        try! self.realm.write {
            self.realm.add(sprite)
        }
    }
```

This triggers the following error **Property 'position' is declared as 'CGPoint', which is not a supported RLMObject property type. All properties must be primitives, NSString, NSDate, NSData, NSNumber, RLMArray, RLMLinkingObjects, RLMDecimal128, RLMObjectId, or subclasses of RLMObject. See https://realm.io/docs/objc/latest/api/Classes/RLMObject.html for more information. (RLMException)**

**Comment by quentinfasquel** [comment]
What I would expect to be able to do is somehow this :
```
extension CGFloat: RealmableEnum {
    public func rlmValue() -> Any {
        Float(self)
    }
    
    public init?(rlmValue: Any) {
        self = CGFloat(rlmValue as? Float ?? 0)
    }

    public static var rawValueType: Any.Type {
        Float.self
    }
}

extension CGSize: RealmableEnum {
    public func rlmValue() -> Any {
        NSNumber(cgSize: self)
    }
    
    public init?(rlmValue: Any) {
        self = (rlmValue as? NSNumber)?.cgSizeValue ?? .zero
    }
    
    public static var rawValueType: Any.Type {
        NSNumber.self
    }
}

extension CGPoint: RealmableEnum {
    public func rlmValue() -> Any {
        NSNumber(cgPoint: self)
    }
    
    public init?(rlmValue: Any) {
        self = (rlmValue as? NSNumber)?.cgPointValue ?? .zero
    }
    
    public static var rawValueType: Any.Type {
        NSNumber.self
    }
}
```

But this ends up to the same error. Do you think possible to automatically implement `RawRepresentable` as direct values (not objects) when the RawValue is a supported type ?

**Comment by arturdev** [comment]
You can't save tuples, but I'll try to add support of CG types

**Comment by arturdev** [comment]
I've found out that CG type (CoreGraphics) shouldn't be stored in the realm. Therefore I leave it as it
