### ISSUE TITLE
Please update to support Realm 10.7.4

### ISSUE THREAD

**Issue by ionut-lucaci** [arturdev/Unrealm#55]
https://github.com/realm/realm-cocoa/issues/7228 -> This issue was solved in this version and it's holding us from releasing the app which **must** support a deployment target of iOS 12. Thanks

**Comment by arturdev** [comment]
Will do during the next two days

**Comment by kevin-zqw** [comment]
Thanks very much, I also need this new version.

**Comment by arturdev** [comment]
Done!
