### ISSUE TITLE
Crash in Realm+Unrealm.swift

### ISSUE THREAD

**Issue by HasanYaakoubToothpick** [arturdev/Unrealm#56]
Could not cast value of type 'RLMUser' to 'RealmSwiftObject'.
Line 38 
`let cls = (NSClassFromString(realmClass) ?? NSClassFromString(realmTypeName)) as! Object.Type`
this is crashing when I am trying to call `realm.objects(User.self)`

**Comment by arturdev** [comment]
Hi. 
The thing is that in the Realm source code there is already a class called RLMUser. 
So in your "User" class you should override the rlm prefix to something else to not conflict with Realm's RLMUser.

**Comment by HasanYaakoubToothpick** [comment]
Hello @arturdev 

I was facing this issue and searched a lot for a solution but found nothing,
The exception message was misleading.
I tried to override `realmClassPrefix` it works for me

Thank you
