### ISSUE TITLE
Problem using enum

### ISSUE THREAD

**Issue by flocked** [arturdev/Unrealm#59]
I'm trying to use an enum. This is my code:

```
// AppDelegate
func applicationWillFinishLaunching(_ notification: Notification) {
Realm.registerRealmables([Book.self], enums: [Genre.self])
}

enum Genre: String, RealmableEnumString, CaseIterable, Codable {
    case action = "action"
    case fantasy = "fantasy"
// … 
}


class Book: Realmable, Hashable, Codable {
    var name = ""
    var genre: Genre?
    var id = UUID().uuidString
   static func primaryKey() -> String? {
        return "id"
    }
    required init() {
    }
}
```

This gives me the error:
`Property 'genre' is declared as 'Genre', which is not a supported RLMObject property type. All properties must be primitives, NSString, NSDate, NSData, NSNumber, RLMArray, RLMLinkingObjects, or subclasses of RLMObject.
`

It seems the Genre enum isn't registered. Any idea why?

**Comment by flocked** [comment]
Just found out that Enums can't be optional.
It would be useful to add this information to the readme :)

**Comment by arturdev** [comment]
In the readme is listed all the supported types :) Optional enums is not listed there ;)
