### ISSUE TITLE
can't build on xCode 13 RC 

### ISSUE THREAD

**Issue by anacronistico** [arturdev/Unrealm#60]
Hi,
 pod can't be build on xCode 13 RC. I think unrealm need to update its realm dependency to last version

**Comment by ionut-lucaci** [comment]
Hello, in the meantime xcode 13 has been released and unrealm still does not work.

**Comment by arturdev** [comment]
i'm currently looking into it

**Comment by arturdev** [comment]
I just released a new version.
Please try this one

**Comment by ionut-lucaci** [comment]
It does work, thanks a lot!!!
