### ISSUE TITLE
Xcode 13 support 

### ISSUE THREAD

**Issue by MercurialKZ** [arturdev/Unrealm#63]
![2021-11-19 10 32 22](https://user-images.githubusercontent.com/36929402/142565343-8af367fe-8762-497c-8212-841a4c67255f.jpg)

**Comment by arturdev** [comment]
Are you sure that the Realm pod itself is compatible with your project?

**Comment by MercurialKZ** [comment]
> Are you sure that the Realm pod itself is compatible with your project?

compatible, Xcode 12.5.1 everything works, but in  13  can not run

**Comment by MercurialKZ** [comment]
version  pod 'Unrealm', '1.9.1'

**Comment by arturdev** [comment]
I mean, according to the screenshot you posted, the issue is with the RealmSwift framework, and not from Unrealm framework.  Please, try to install only RealmSwift framework without Unrealm to make sure that the RealmSwift itself works for you.

**Comment by MercurialKZ** [comment]
thanks

**Comment by MercurialKZ** [comment]
<img width="325" alt="Снимок экрана 2021-11-19 в 15 43 44" src="https://user-images.githubusercontent.com/36929402/142601386-339dd979-df46-4588-9ef8-ffbed4572794.png">
can u update RealmSwift version

**Comment by arturdev** [comment]
the podspec of Unrealm always points to the latest version of Realm/RealmSwift. 
Try to do "pod update --repo-update"

**Comment by MercurialKZ** [comment]
thanks )
