### ISSUE TITLE
- There must be a primary key property named '_id' on a synchronized Realm but none was found for type 'RLMOptional'

### ISSUE THREAD

**Issue by abaig-experlabs** [arturdev/Unrealm#64]
Hey I am facing this issue while trying to add data with realm swift
is RLMOptional a custom data type of unrealm?
@arturdev

**Comment by arturdev** [comment]
Hi. No, RLMOptional is one of the Realm's native types

**Comment by abaig-experlabs** [comment]
Hi, do you have any idea why I get this error?

**Comment by abaig-experlabs** [comment]
i just debugged a little and it seems like the unrealm is treating optional custom objects like this which is causing the error
@arturdev 

<img width="573" alt="Screen Shot 2021-11-26 at 7 34 08 PM" src="https://user-images.githubusercontent.com/61403191/143596462-c1b58e6a-0f46-4a5f-9c05-5b672628f3c0.png">

**Comment by arturdev** [comment]
So far my unit tests pass successfully: 
https://github.com/arturdev/Unrealm/blob/master/Example/Tests/ExampleModels/User.swift#L25
